# Generated by Django 5.1.7 on 2025-10-09 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's name", max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('listing', 'Listing Problem'), ('event', 'Event Issue'), ('account', 'Account Problem'), ('feedback', 'Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('other', 'Other')], default='general', help_text='Type of help request', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject/title of the issue', max_length=255)),
                ('message', models.TextField(help_text='Detailed description of the issue or request')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the request', max_length=15)),
                ('admin_response', models.TextField(blank=True, help_text='Admin response to the request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin who responded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help & Support Request',
                'verbose_name_plural': 'Help & Support Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
