# Generated by Django 5.1.7 on 2025-10-09 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_helpsupport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Contact person's name", max_length=100)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('company_name', models.CharField(help_text='Company or organization name', max_length=150)),
                ('website', models.URLField(blank=True, help_text='Company website (optional)', max_length=500)),
                ('collaboration_type', models.CharField(choices=[('business', 'Business Partnership'), ('event', 'Event Collaboration'), ('marketing', 'Marketing Partnership'), ('sponsorship', 'Sponsorship'), ('content', 'Content Creation'), ('tourism', 'Tourism Partnership'), ('restaurant', 'Restaurant/Food Business'), ('retail', 'Retail/Shopping'), ('services', 'Professional Services'), ('other', 'Other Collaboration')], help_text='Type of collaboration', max_length=20)),
                ('company_size', models.CharField(choices=[('individual', 'Individual/Freelancer'), ('small', 'Small Business (1-10 employees)'), ('medium', 'Medium Business (11-50 employees)'), ('large', 'Large Business (50+ employees)'), ('government', 'Government/Public Sector'), ('nonprofit', 'Non-profit Organization')], help_text='Size of your organization', max_length=15)),
                ('proposal', models.TextField(help_text='Detailed collaboration proposal')),
                ('budget_range', models.CharField(blank=True, help_text='Budget range (if applicable)', max_length=100)),
                ('timeline', models.CharField(blank=True, help_text='Preferred timeline', max_length=100)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile', max_length=500)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile', max_length=500)),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio or additional work samples', max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('interested', 'Interested'), ('scheduled', 'Meeting Scheduled'), ('declined', 'Declined'), ('completed', 'Collaboration Started')], default='new', help_text='Current status of the collaboration request', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_collaborations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the collaboration request', on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaboration Contact',
                'verbose_name_plural': 'Collaboration Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
