# Generated by Django 5.1.7 on 2025-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collaborationcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='collaborationcontact',
            name='website',
        ),
        migrations.AlterField(
            model_name='collaborationcontact',
            name='collaboration_type',
            field=models.CharField(choices=[('business', 'Business Partnership'), ('event', 'Event Collaboration'), ('marketing', 'Marketing Partnership'), ('tourism', 'Tourism Partnership'), ('other', 'Other Collaboration')], help_text='Type of collaboration', max_length=20),
        ),
    ]
