# Generated by Django 5.1.7 on 2025-10-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_collaborationcontact_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_events',
            field=models.BooleanField(default=True, help_text='Whether this category should be available for events'),
        ),
    ]
