# Generated by Django 5.1.7 on 2025-10-12 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_show_in_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for guest user', unique=True)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('mk', 'Macedonian')], default='en', help_text="Guest user's preferred language", max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
    ]
