# Generated by Django 5.1.7 on 2025-10-12 14:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_guestuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Listing image stored in the media bucket', null=True, upload_to=core.models.listing_image_upload_to),
        ),
    ]
