# Generated by Django 5.1.7 on 2025-10-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='promotions',
            field=models.ManyToManyField(blank=True, help_text='Select promotions associated with this listing (optional)', related_name='listings', to='core.promotion'),
        ),
    ]
