# Generated by Django 5.1.7 on 2025-10-13 15:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_listing_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Promotion image stored in the media bucket', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
    ]
