# Generated by Django 5.1.7 on 2025-10-13 23:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_promotion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Optional additional listing image', null=True, upload_to=core.models.listing_image_upload_to),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Optional additional listing image', null=True, upload_to=core.models.listing_image_upload_to),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Optional additional listing image', null=True, upload_to=core.models.listing_image_upload_to),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Optional additional listing image', null=True, upload_to=core.models.listing_image_upload_to),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Optional additional listing image', null=True, upload_to=core.models.listing_image_upload_to),
        ),
    ]
