# Generated by Django 5.1.7 on 2025-10-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_listing_image_1_listing_image_2_listing_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_time',
            field=models.CharField(blank=True, help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tags, e.g., ['Grill', 'Family', 'Outdoor']", null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags_mk',
            field=models.JSONField(blank=True, default=list, help_text="List of tags in Macedonian, e.g., ['Скара', 'Семејно', 'Надворешно']", null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Working hours structure, e.g., {'monday': '09:00-18:00', 'tuesday': '09:00-18:00', ...}", null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='working_hours_mk',
            field=models.JSONField(blank=True, default=dict, help_text="Working hours in Macedonian, e.g., {'понedelник': '09:00-18:00', 'вторник': '09:00-18:00', ...}", null=True),
        ),
    ]
