# Generated by Django 5.1.7 on 2025-10-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_listing_tags_alter_listing_tags_mk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_time_en',
            field=models.CharField(blank=True, help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='open_time_mk',
            field=models.CharField(blank=True, help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100, null=True),
        ),
    ]
