# Generated by Django 5.1.7 on 2025-10-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_listing_open_time_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_time',
            field=models.CharField(blank=True, help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100, null=True),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_listing ALTER COLUMN open_time DROP NOT NULL;",
            reverse_sql="ALTER TABLE core_listing ALTER COLUMN open_time SET NOT NULL;",
        ),
    ]
