# Generated by Django 5.1.7 on 2025-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_make_open_time_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text="List of amenities with optional icon, e.g., [{'icon': 'wifi', 'text': 'Free Wi-Fi'}]", null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities_mk',
            field=models.JSONField(blank=True, default=list, help_text="List of amenities in Macedonian, e.g., [{'icon': 'wifi', 'text': 'Бесплатен Wi-Fi'}]", null=True),
        ),
    ]
