# Generated by Django 5.1.7 on 2025-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listing_amenities_listing_amenities_mk'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities_title',
            field=models.CharField(blank=True, default='Amenities', help_text="Custom title for the amenities section (e.g., 'Features', 'What We Offer', 'Services')", max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities_title_mk',
            field=models.CharField(blank=True, default='Погодности', help_text='Custom title for the amenities section in Macedonian', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='show_open_status',
            field=models.BooleanField(default=False, help_text='Enable this to show Open/Closed status based on working hours'),
        ),
    ]
