# Generated by Django 5.2.14 on 2026-05-05 17:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_alter_verificationcode_email_and_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promo', 'Promotion'), ('spotlight', 'Spotlight'), ('announcement', 'Announcement'), ('countdown', 'Countdown Event')], default='spotlight', help_text='Type of billboard item', max_length=20)),
                ('section', models.CharField(choices=[('hero', 'Hero Section'), ('limited', 'Limited Time'), ('spotlight', 'Spotlight'), ('upcoming', 'Coming Soon'), ('general', 'General')], default='general', help_text='Which section this item appears in', max_length=20)),
                ('title', models.CharField(help_text='Main title', max_length=200)),
                ('title_mk', models.CharField(blank=True, help_text='Title in Macedonian', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle or description')),
                ('subtitle_mk', models.TextField(blank=True, help_text='Subtitle in Macedonian')),
                ('image', models.ImageField(blank=True, help_text='Main billboard image', null=True, upload_to=core.models.billboard_image_upload_to)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, help_text='External URL (if not linking to internal content)')),
                ('button_text', models.CharField(default='Learn More', help_text='Call-to-action button text', max_length=50)),
                ('button_text_mk', models.CharField(blank=True, help_text='Button text in Macedonian', max_length=50)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When this item becomes visible', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this item expires (also used for countdown)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within section')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items get priority display')),
                ('background_color', models.CharField(default='#B91C1C', help_text='Background color (hex)', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color (hex)', max_length=7)),
                ('tag', models.CharField(blank=True, help_text="Badge/tag text (e.g., 'HOT', 'NEW', '50% OFF')", max_length=50)),
                ('tag_mk', models.CharField(blank=True, help_text='Tag in Macedonian', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billboard Item',
                'verbose_name_plural': 'Billboard Items',
                'ordering': ['section', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Section title displayed on Billboard (e.g., 'Travel Guides', 'Food & Dining')", max_length=100)),
                ('label_mk', models.CharField(blank=True, help_text='Section title in Macedonian', max_length=100)),
                ('card_type', models.CharField(choices=[('small', 'Small Cards'), ('big', 'Big Cards'), ('carousel', 'Carousel')], default='big', help_text='Visual style: small (compact list), big (large cards), or carousel (auto-scrolling)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on Billboard (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section on the Billboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billboard Section',
                'verbose_name_plural': 'Billboard Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillboardSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the section (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in the section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billboard Section Item',
                'verbose_name_plural': 'Billboard Section Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_mk', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Section content')),
                ('content_en', models.TextField(blank=True)),
                ('content_mk', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_expanded_by_default', models.BooleanField(default=False, help_text='Whether this section is expanded when the page loads')),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('listing', 'Listing'), ('event', 'Event'), ('promotion', 'Promotion')], default='listing', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('card_size', models.CharField(choices=[('hero', 'Hero (Full Width)'), ('large', 'Large (2-Column)'), ('medium', 'Medium (3-Column)'), ('small', 'Small (Horizontal Scroll)')], default='medium', max_length=10)),
                ('promo_text', models.CharField(blank=True, help_text="e.g., '20% Off Today!'", max_length=100)),
                ('promo_text_mk', models.CharField(blank=True, max_length=100)),
                ('valid_until', models.DateTimeField(blank=True, help_text='For countdown timer', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Item',
                'verbose_name_plural': 'Featured Items',
                'ordering': ['card_size', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.gallery_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_mk', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourismCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Carousel item title', max_length=200)),
                ('title_en', models.CharField(blank=True, help_text='Title in English', max_length=200)),
                ('title_mk', models.CharField(blank=True, help_text='Title in Macedonian', max_length=200)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the referenced object')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in carousel (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tourism Carousel Item',
                'verbose_name_plural': 'Tourism Carousel Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourismCategoryButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Button label (e.g., 'Restaurants', 'Hotels')", max_length=100)),
                ('label_en', models.CharField(blank=True, help_text='Label in English', max_length=100)),
                ('label_mk', models.CharField(blank=True, help_text='Label in Macedonian', max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'restaurant', 'hotel', 'coffee') - for frontend to handle", max_length=50)),
                ('background_image', models.ImageField(blank=True, help_text='Optional background image for the button (displays instead of red gradient when set)', null=True, upload_to=core.models.tourism_button_bg_upload_to)),
                ('button_size', models.CharField(choices=[('small', 'Small Button'), ('big', 'Big Button')], default='small', help_text='Button size: small (4 in row) or big (2 in row)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this button on tourism screen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tourism Category Button',
                'verbose_name_plural': 'Tourism Category Buttons',
                'ordering': ['button_size', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameIndex(
            model_name='homesection',
            new_name='core_homese_is_acti_66c62c_idx',
            old_name='core_homese_is_acti_2ef31d_idx',
        ),
        migrations.RenameIndex(
            model_name='homesectionitem',
            new_name='core_homese_section_81694d_idx',
            old_name='core_homese_section_2ca60f_idx',
        ),
        migrations.RenameIndex(
            model_name='homesectionitem',
            new_name='core_homese_content_aecd38_idx',
            old_name='core_homese_content_197534_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_subtitle',
            field=models.CharField(blank=True, help_text="Subtitle below button (e.g., 'Opens in Browser')", max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_subtitle_en',
            field=models.CharField(blank=True, help_text='Button subtitle in English', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_subtitle_mk',
            field=models.CharField(blank=True, help_text='Button subtitle in Macedonian', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_title',
            field=models.CharField(blank=True, help_text="Button text (e.g., 'Book Now', 'Learn More')", max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_title_en',
            field=models.CharField(blank=True, help_text='Button text in English', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_title_mk',
            field=models.CharField(blank=True, help_text='Button text in Macedonian', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='cta_button_url',
            field=models.URLField(blank=True, help_text='URL the button leads to', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary blog image stored in the media bucket', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Optional additional blog image', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Optional additional blog image', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Optional additional blog image', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Optional additional blog image', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Optional additional blog image', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this blog in the app. Uncheck to hide from users.'),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for list/card views (recommended: 430x430px). If not set, auto-generated from main image.', null=True, upload_to=core.models.blog_image_upload_to),
        ),
        migrations.AddField(
            model_name='category',
            name='applies_to',
            field=models.CharField(choices=[('listing', 'Listing'), ('event', 'Event'), ('both', 'Both')], default='both', help_text='Whether this category applies to listings, events, or both', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text="Brand color for category in hex format (e.g., '#FF5722')", max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description (will be translated by modeltranslation)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, help_text='Category description (will be translated by modeltranslation)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_mk',
            field=models.TextField(blank=True, help_text='Category description (will be translated by modeltranslation)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as featured category'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional category image stored in the media bucket', null=True, upload_to=core.models.category_image_upload_to),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether category is active and visible'),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Hierarchy level (0=root, 1=subcategory, etc.)'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within parent category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (leave empty for root categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_navigation',
            field=models.BooleanField(default=True, help_text='Show in navigation menus'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_search',
            field=models.BooleanField(default=True, help_text='Show in search screen'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if empty)', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for directions (optional - if not provided, will use location field)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary event image stored in the media bucket', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Optional additional event image', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Optional additional event image', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Optional additional event image', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Optional additional event image', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Optional additional event image', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this event in the app. Uncheck to hide from users.'),
        ),
        migrations.AddField(
            model_name='event',
            name='listings',
            field=models.ManyToManyField(blank=True, help_text='Select listings associated with this event (optional)', related_name='events', to='core.listing'),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number (shown when join button is disabled)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Sections this event should appear in', related_name='direct_events', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_join_button',
            field=models.BooleanField(default=True, help_text="Show 'Join Event' button. If unchecked, show 'Contact' button instead."),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for list/card views (recommended: 430x430px). If not set, auto-generated from main image.', null=True, upload_to=core.models.event_image_upload_to),
        ),
        migrations.AddField(
            model_name='event',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='blogs',
            field=models.ManyToManyField(blank=True, help_text='Select blog articles related to this listing (optional)', related_name='listings', to='core.blog'),
        ),
        migrations.AddField(
            model_name='listing',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for directions (optional - if not provided, will use address field)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this listing in the app. Uncheck to hide from users.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='manual_open_status',
            field=models.BooleanField(blank=True, default=True, help_text='Manually set Open/Closed status (used when working hours are not defined). True = Open, False = Closed, Null = Use working hours', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='menu',
            field=models.JSONField(blank=True, default=list, help_text='Menu sections in English, e.g. [{"heading": "Coffee", "items": [{"name": "Espresso", "price": "80"}, {"name": "Water"}]}]', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='menu_icon',
            field=models.CharField(blank=True, choices=[('restaurant-outline', 'Restaurant / Food'), ('cafe-outline', 'Café / Coffee'), ('beer-outline', 'Bar / Drinks'), ('fitness-outline', 'Gym / Fitness'), ('school-outline', 'Education / School'), ('cut-outline', 'Beauty / Barber'), ('medical-outline', 'Medical / Health'), ('briefcase-outline', 'Services / Business'), ('pricetag-outline', 'Pricing / Plans'), ('list-outline', 'General List'), ('construct-outline', 'Repair / Technical'), ('leaf-outline', 'Nature / Spa')], default='restaurant-outline', help_text='Icon displayed on the menu button in the app.', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='Button label in English (e.g. "Menu", "Memberships", "Services"). Leave blank to use "Menu".', max_length=80),
        ),
        migrations.AddField(
            model_name='listing',
            name='menu_label_mk',
            field=models.CharField(blank=True, default='', help_text='Button label in Macedonian. Leave blank to use "Мени".', max_length=80),
        ),
        migrations.AddField(
            model_name='listing',
            name='menu_mk',
            field=models.JSONField(blank=True, default=list, help_text='Menu sections in Macedonian, same structure as menu field', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='random_order',
            field=models.DecimalField(db_index=True, decimal_places=9, default=0.5, help_text='Random value for shuffling order (auto-updated by cron job for fair rotation)', max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Sections this listing should appear in', related_name='direct_listings', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='listing',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for list/card views (recommended: 430x430px). If not set, auto-generated from main image.', null=True, upload_to=core.models.listing_image_upload_to),
        ),
        migrations.AddField(
            model_name='listing',
            name='trending',
            field=models.BooleanField(default=False, help_text='Mark as trending - will be displayed in trending tab on search screen'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for directions (optional - if not provided, will use address field)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Optional additional promotion image', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Optional additional promotion image', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Optional additional promotion image', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Optional additional promotion image', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Optional additional promotion image', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this promotion in the app. Uncheck to hide from users.'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Sections this promotion should appear in', related_name='direct_promotions', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for list/card views (recommended: 430x430px). If not set, auto-generated from main image.', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('default', 'Default (Initial)'), ('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3'), ('avatar4', 'Avatar 4'), ('avatar5', 'Avatar 5'), ('avatar6', 'Avatar 6'), ('avatar7', 'Avatar 7'), ('avatar8', 'Avatar 8'), ('avatar9', 'Avatar 9'), ('avatar10', 'Avatar 10')], default='default', help_text='Selected profile avatar', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='home_sections',
            field=models.ManyToManyField(blank=True, help_text='Home sections this blog should appear in', related_name='direct_blogs', to='core.homesection'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (will be translated by modeltranslation)', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Category name (will be translated by modeltranslation)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_mk',
            field=models.CharField(help_text='Category name (will be translated by modeltranslation)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_events',
            field=models.BooleanField(default=True, help_text='[Legacy] Whether this category should be available for events'),
        ),
        migrations.AlterField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='Mark as trending category (can be combined with featured)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.CharField(blank=True, default='All ages welcome', help_text="Age restriction (e.g., 'All ages welcome', '18+', '21+')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit_mk',
            field=models.CharField(blank=True, help_text="Age restriction in Macedonian (e.g., 'Добредојдени се сите возрасти', '18+', '21+')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_price',
            field=models.CharField(blank=True, default='Free', help_text="Entry price (e.g., 'Free', '10 EUR', '500 MKD')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_price_mk',
            field=models.CharField(blank=True, help_text="Entry price in Macedonian (e.g., 'Бесплатно', '10 ЕУР', '500 МКД')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary promotion image stored in the media bucket', null=True, upload_to=core.models.promotion_image_upload_to),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', 'is_active', 'published'], name='core_blog_categor_181051_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['featured', 'published', '-created_at'], name='core_blog_feature_3983b9_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_active', 'published', '-created_at'], name='core_blog_is_acti_8e9f35_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='core_catego_parent__68b602_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'order'], name='core_catego_level_ede8af_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'is_active'], name='core_event_categor_ab61a9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['featured', '-date_time'], name='core_event_feature_e3c85c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', '-date_time'], name='core_event_is_acti_a92276_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'is_active'], name='core_listin_categor_cabb66_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['featured', '-created_at'], name='core_listin_feature_39aa20_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['trending', '-created_at'], name='core_listin_trendin_b11a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active', '-created_at'], name='core_listin_is_acti_d9de5a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['featured', 'is_active', '-created_at'], name='core_promot_feature_040b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', '-created_at'], name='core_promot_is_acti_12580e_idx'),
        ),
        migrations.AddField(
            model_name='billboarditem',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Link to internal content (optional)', limit_choices_to={'model__in': ('listing', 'event', 'promotion')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='billboardsection',
            index=models.Index(fields=['is_active', 'order'], name='core_billbo_is_acti_ae4c30_idx'),
        ),
        migrations.AddField(
            model_name='billboardsectionitem',
            name='blog',
            field=models.ForeignKey(help_text='Select a blog article', on_delete=django.db.models.deletion.CASCADE, related_name='billboard_items', to='core.blog'),
        ),
        migrations.AddField(
            model_name='billboardsectionitem',
            name='section',
            field=models.ForeignKey(help_text='The section this blog belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.billboardsection'),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='core.blog'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['listing', 'event', 'promotion']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Assign to a specific listing, or leave blank for the main city gallery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_photos', to='core.listing'),
        ),
        migrations.AddField(
            model_name='tourismcarousel',
            name='content_type',
            field=models.ForeignKey(help_text='Type of content (Listing, Event, or Blog)', limit_choices_to={'model__in': ('listing', 'event', 'blog')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tourismcategorybutton',
            name='category',
            field=models.ForeignKey(help_text='Category to link to', on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddIndex(
            model_name='billboarditem',
            index=models.Index(fields=['is_active', 'section', 'order'], name='core_billbo_is_acti_77618c_idx'),
        ),
        migrations.AddIndex(
            model_name='billboarditem',
            index=models.Index(fields=['item_type', 'is_active'], name='core_billbo_item_ty_91d478_idx'),
        ),
        migrations.AddIndex(
            model_name='billboarditem',
            index=models.Index(fields=['expires_at'], name='core_billbo_expires_6d419a_idx'),
        ),
        migrations.AddIndex(
            model_name='billboardsectionitem',
            index=models.Index(fields=['section', 'is_active', 'order'], name='core_billbo_section_e8b618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billboardsectionitem',
            unique_together={('section', 'blog')},
        ),
        migrations.AlterUniqueTogether(
            name='featureditem',
            unique_together={('content_type', 'object_id', 'card_size')},
        ),
        migrations.AddIndex(
            model_name='tourismcarousel',
            index=models.Index(fields=['is_active', 'order'], name='core_touris_is_acti_b5383c_idx'),
        ),
        migrations.AddIndex(
            model_name='tourismcarousel',
            index=models.Index(fields=['content_type', 'object_id'], name='core_touris_content_25d7b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourismcarousel',
            unique_together={('content_type', 'object_id')},
        ),
    ]
